# Generated by Django 4.2.7 on 2023-11-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимость')),
                ('first_name', models.CharField(default='Имя', max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(default='Фамилия', max_length=255, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, default='Отчество', max_length=255, verbose_name='Отчество')),
                ('about_us', models.TextField(verbose_name='Обо мне')),
                ('image', models.ImageField(blank=True, upload_to='my_photo/%Y/%m/%d', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Обо мне',
            },
        ),
    ]
